name_user_maximum: 50
email_maximum: 255
password_minimum: 6
maximum_content: 500
maximum_name: 255
minimum_quantity: 0
maximum_address: 255
per_page: 10
gravatar_size: 80
gravatar_size_50: 50
collect_from: 1
collect_to: 99
maximum_price: 1000000000
minimum_price: 0
maximum_name: 50
resize_to_fit_width: 50
resize_to_fit_height: 50
limit_info: 70
domain: http://localhost:3000/
facebook:
  app_id: 1481111758594390
